const MoviesPosters = [
    {
        id:"a",
        name:"ELLA ENCHANTED",
        release_date:"2004",
        directedBy: "TOMMY O'HAVER",
        writenBy :"LAUREN CRAING, McCULLAH LUTZ",
        producedBy: "SUSAN MILLER, JANE STARTZ",
        img:"https://th.bing.com/th/id/OIP.UIcbeomA6mPUSAAS7PR-oAHaKc?rs=1&pid=ImgDetMain",
    },
    {
        id:"b",
        name:" ENCHANTED",
        release_date:"2007",
        directedBy: "KELVIN LIMA",
        writenBy :"McCULLAH LUTZ",
        producedBy: "BARRY JOSEPHSON,IDINA MENZEL",
        img:"https://i.pinimg.com/originals/71/b7/7d/71b77d49fef1751499000519255b4c9c.jpg",
    },
    {
        id:"c",
        name:"Inside Out 2 ",
        release_date:"8 may , 2024",
        directedBy: "Pete Docter,Kelsey Mann",
        writenBy :"	Meg LeFauve",
        producedBy: "Maya Hawke, Diane Lane,",
        img:"https://images.flickdirect.com/cache/movies/inside-out-2/05000-inside-out-2-poster.jpg",
    },
    {
        id:"d",
        name:"Bad Boys Ride or Die  ",
        release_date:"June 7, 2024",
        directedBy: "Adil El Arbi , Bilall Fallah",
        writenBy :"Chris Bremner , George Gallo",
        producedBy: " Will Smith, Martin Lawrence, Vanessa Hudgens",
        img:"https://th.bing.com/th/id/OIP.5E5wbl_VpS-fbxsgfbishgHaJQ?rs=1&pid=ImgDetMain",
    },
    {
        id:"e",
        name:"Despicable Me 4  ",
        release_date:"julay 3,2024",
        directedBy: "Chris Renaud , Patrick Delag",
        writenBy :"Mike White ,Ken Daurio",
        producedBy: "Universal Pictures and Illumination ",
        img:"https://th.bing.com/th/id/OIP.qEpJmIbKQjvoZG-UvtOPoAAAAA?rs=1&pid=ImgDetMain",
    },
    {
        id:"f",
        name:"Brave Citizen",
        release_date:"25 Aug, 2023",
        directedBy: " Park Jin-Pyo",
        writenBy :" Ji Na Yeo",
        producedBy: "Jenna Ku",
        img:"https://th.bing.com/th/id/R.0b977ce07887eeaa2dfd32b7d6104823?rik=vdwDrelmF4WIxQ&riu=http%3a%2f%2fwww.wazzup.ph%2fwp-content%2fuploads%2f2021%2f05%2fGuem-Sae-Rok-Youth-of-May-Now-Streaming-on-Viu-Philippines.jpg&ehk=GZbo9Hg4JzolIPPz71v%2f7B2%2b70rE2dRWKyXL%2fFdf24w%3d&risl=&pid=ImgRaw&r=0",
    },
    {
        id:"g",
        name:"Crash Landing On You: Live in Seoul",
        release_date:"30 nov,2024",
        directedBy: "Jaeseok Park ",
        writenBy :"Park Ji-Eun ",
        producedBy: "Wys En Scène",
        img:"https://i.pinimg.com/736x/65/c7/c8/65c7c878c77f0434fe3820f84bd8377b.jpg",
    },
    {
        id:"h",
        name:"WAR",
        release_date:"October 2, 2019",
        directedBy: "  Siddharth Anand",
        writenBy :"Siddharth Anand, Aditya Chopra, Shridhar Raghavan ",
        producedBy: "Aditya Chopra",
        img:"https://th.bing.com/th/id/OIP.u_4EmY47GFSs0w4RbcFAugHaHa?rs=1&pid=ImgDetMain",
    },
    {
        id:"i",
        name:"RAAZI",
        release_date:"May 11,2018",
        directedBy: "Meghna Gulzar ",
        writenBy :"Harinder S. SikkaMeghna GulzarBhavani Iyer",
        producedBy: " Vineet Jain, Karan Johar, Hiroo Yash Johar",
        img:"https://th.bing.com/th/id/OIP.529--3GJLeUf10xnsriD_AHaKs?rs=1&pid=ImgDetMain",
    },
];
export default MoviesPosters;